### ISSUE TITLE
Cloudflare worker deployment

### ISSUE THREAD

**Issue by hawcgn** [CorentinTh/enclosed#294] opened 2024-10-17 17:23 UTC
### What type of request is this?

Deployment or CI/CD improvement

### Clear and concise description of the feature you are proposing

Is there a cloudflare worker deployment method?

### Additional context

Hi! I can't find cloudflare worker deployment in the documentation, but looking at the source code you have wrangler.toml.
So is there any documentation for worker deployment？ Like this one：[worker-deploy](https://github.com/SharzyL/pastebin-worker/tree/goshujin?tab=readme-ov-file#deploy)

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment] 2024-10-17 18:47
Hi @hawcgn 

Duplicate of #258, I'll add a page in the documentation to explicit the deployment on cloudflare

**Comment by hawcgn** [comment] 2024-10-18 00:15
Okay, I see that, but I'm hoping to see a documented approach to page deployment soon. Thanks.

**Closed** 2024-10-18 00:16 UTC
Labels: enhancement
